<a href="https://colab.research.google.com/github/prashantbhoye2003-debug/Development-of-a-Healthcare-Operations-Intelligence-Dashboard-with-Decision-Analytics/blob/main/sql_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##<b>SQL Task : Patient Database Management using SQLite and Pandas</b>

####<b>Prompt :</b> Write a Python program using SQLite and Pandas to create an patient database, insert sample patient records, perform SQL queries (filtering, grouping, aggregation, sorting), display the results, delete a specific petient record, and save the changes

In [1]:
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
# This means the database will only exist for the duration of the script
conn = sqlite3.connect(':memory:')
c = conn.cursor()

# Create the patients table
c.execute('''
    CREATE TABLE patients (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER,
        gender TEXT,
        city TEXT
    )
''')
print("Patients table created successfully.")

Patients table created successfully.

###Step 1: Insert Sample Patient Records

We'll create a Pandas DataFrame with sample data and then insert these records into our `patients` table.

In [2]:
# Sample patient data using a Pandas DataFrame
data = {
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams', 'Frank White'],
    'age': [30, 45, 25, 55, 32, 40],
    'gender': ['Female', 'Male', 'Male', 'Female', 'Female', 'Male'],
    'city': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Chicago', 'Houston']
}
df_patients = pd.DataFrame(data)

# Insert DataFrame into SQLite table
df_patients.to_sql('patients', conn, if_exists='append', index=False)
print("Sample patient records inserted.")

# Display all records to verify insertion
print("\nAll patient records:")
display(pd.read_sql_query("SELECT * FROM patients", conn))

Sample patient records inserted.

All patient records:

   id           name  age  gender         city
0   1    Alice Smith   30  Female     New York
1   2    Bob Johnson   45    Male  Los Angeles
2   3  Charlie Brown   25    Male      Chicago
3   4   Diana Prince   55  Female     New York
4   5      Eve Adams   32  Female      Chicago
5   6    Frank White   40    Male      Houston

###Step 2: Perform SQL Queries

Now, let's perform various SQL queries using `pd.read_sql_query` to fetch data directly into Pandas DataFrames.

In [3]:
# 1. Filtering: Select patients older than 35
print("\nPatients older than 35:")
filtered_df = pd.read_sql_query("SELECT * FROM patients WHERE age > 35", conn)
display(filtered_df)

# 2. Grouping and Aggregation: Count patients by city
print("\nPatient count by city:")
grouped_df = pd.read_sql_query("SELECT city, COUNT(id) AS patient_count FROM patients GROUP BY city", conn)
display(grouped_df)

# 3. Sorting: Select all patients and sort by age in descending order
print("\nAll patients sorted by age (descending):")
sorted_df = pd.read_sql_query("SELECT * FROM patients ORDER BY age DESC", conn)
display(sorted_df)

Patients older than 35:

   id          name  age  gender         city
0   2   Bob Johnson   45    Male  Los Angeles
1   4  Diana Prince   55  Female     New York
2   6   Frank White   40    Male      Houston

Patient count by city:

          city  patient_count
0      Chicago              2
1      Houston              1
2  Los Angeles              1
3     New York              2

All patients sorted by age (descending):

   id           name  age  gender         city
0   4   Diana Prince   55  Female     New York
1   2    Bob Johnson   45    Male  Los Angeles
2   6    Frank White   40    Male      Houston
3   5      Eve Adams   32  Female      Chicago
4   1    Alice Smith   30  Female     New York
5   3  Charlie Brown   25    Male      Chicago

###Step 3: Delete a Specific Patient Record

We will delete a patient by their ID and then display the updated records.

In [4]:
# Delete patient with ID 3 (Charlie Brown)
patient_id_to_delete = 3
c.execute("DELETE FROM patients WHERE id = ?", (patient_id_to_delete,))
conn.commit() # Commit the changes to the database
print(f"\nPatient with ID {patient_id_to_delete} deleted.")

# Display all records after deletion
print("\nAll patient records after deletion:")
display(pd.read_sql_query("SELECT * FROM patients", conn))

Patient with ID 3 deleted.

All patient records after deletion:

   id          name  age  gender         city
0   1   Alice Smith   30  Female     New York
1   2   Bob Johnson   45    Male  Los Angeles
2   4  Diana Prince   55  Female     New York
3   5     Eve Adams   32  Female      Chicago
4   6   Frank White   40    Male      Houston

###Step 4: Save Changes and Close Connection

Since we are using an in-memory database, saving changes is less critical if we don't plan to persist it. However, `conn.commit()` is good practice for any database modification. Finally, we close the connection.

In [5]:
# Commit any outstanding changes (already done after delete, but good to ensure)
conn.commit()

# Close the database connection
conn.close()
print("Database connection closed.")
print("All operations complete.")

Database connection closed.
All operations complete.